package com.localdevstack.generator

import java.nio.file.Files
import java.nio.file.Path

/**
 * Writes `.env` (resolved values, gitignored) and `.env.example` (placeholders,
 * committed) next to the generated `docker-compose.yml`. The compose file
 * references each value via `${KEY}`, so docker-compose auto-loads `.env`
 * from the same directory.
 */
class EnvFileGenerator {

    fun generate(outputDir: Path, envVars: Map<String, String>) {
        if (envVars.isEmpty()) return
        Files.createDirectories(outputDir)

        Files.writeString(outputDir.resolve(".env"), buildEnv(envVars))
        Files.writeString(outputDir.resolve(".env.example"), buildEnvExample(envVars))
        println("  [OK] .env, .env.example   ->  $outputDir")
    }

    private fun buildEnv(envVars: Map<String, String>): String = buildString {
        appendLine("# Local development environment — auto-generated by LocalDevelopmentStack.")
        appendLine("# These values populate \${VAR} references in docker-compose.yml.")
        appendLine("# Override locally if you need different credentials. Do NOT commit this file.")
        envVars.forEach { (key, value) -> appendLine("$key=${quoteEnvValue(value)}") }
    }

    // Wrap values containing characters that would confuse shells if a user
    // sources `.env` directly. Docker Compose dotenv handles unquoted values
    // fine for most URLs, but `!`, spaces, `#`, quotes and backslashes need
    // quoting so `source .env` in bash doesn't trip on history expansion or
    // word splitting. Common values (postgres / mongo / redis URLs) stay
    // unquoted because they contain none of these characters.
    private fun quoteEnvValue(value: String): String {
        val needsQuoting = value.any { it in " \t#\"'\\!" }
        if (!needsQuoting) return value
        val escaped = value.replace("\\", "\\\\").replace("\"", "\\\"")
        return "\"$escaped\""
    }

    private fun buildEnvExample(envVars: Map<String, String>): String = buildString {
        appendLine("# Example environment — safe to commit.")
        appendLine("# Copy to .env and replace placeholder values before running docker-compose up.")
        envVars.forEach { (key, _) -> appendLine("$key=<change-me>") }
    }
}
