package com.localdevstack.generator

import java.nio.file.Files
import java.nio.file.Path

class RubyDockerfileGenerator : DockerfileGenerator() {

    override fun dockerfile(serviceDir: Path): String =
        if (isRailsApp(serviceDir)) rails() else sinatra()

    // Rails apps always have bin/rails (a stub generated by `rails new`) and
    // config/application.rb (the Rails::Application subclass). Either alone is
    // a strong-enough signal — checking both makes detection robust against
    // partially-checked-in scaffolds.
    private fun isRailsApp(serviceDir: Path): Boolean =
        Files.exists(serviceDir.resolve("bin/rails")) ||
            Files.exists(serviceDir.resolve("config/application.rb"))

    private fun sinatra() = """
        FROM ruby:3.2
        WORKDIR /app
        COPY Gemfile* ./
        RUN bundle install
        EXPOSE 8080
        CMD ["bundle", "exec", "ruby", "app.rb"]
    """.trimIndent()

    private fun rails() = """
        FROM ruby:3.2
        WORKDIR /app
        COPY Gemfile* ./
        RUN bundle install
        EXPOSE 8080
        CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "8080"]
    """.trimIndent()
}
